# paasta-cubrid-vsphere 설정 파일 내용
---
name: paasta-cubrid-service  # 서비스 배포이름(필수)

releases:
- name: paasta-cubrid  #서비스 릴리즈 이름(필수)
  version: "2.0"   #서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

update:
  canaries: 1                                          # canary 인스턴스 수(필수)
  canary_watch_time: 30000-180000                      # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 6                                     # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  update_watch_time: 30000-180000                      # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)

instance_groups:
- name: cubrid  #작업 이름(필수): Cubrid 서버
  azs:
  - z5
  instances: 1                               # job 인스턴스 수(필수)
  vm_type: ((vm_type_small))                 # cloud config 에 정의한 vm_type
  stemcell: default
  persistent_disk_type: 10GB                 # cloud config 에 정의한 영구디스크 사이즈
  networks:
  - name: ((default_network_name))           # cloud config 에 정의한 network 이름
    static_ips:
    - 10.30.107.123                          # 사용할 IP addresses 정의(필수): Cubrid 서버 IP
  templates:
  - name: cubrid
    release: paasta-cubrid

- name: cubrid_broker   #작업 이름(필수): Cubrid 서비스 브로커
  azs:
  - z5
  instances: 1                               # job 인스턴스 수(필수)
  vm_type: ((vm_type_small))                 # cloud config 에 정의한 vm_type
  stemcell: default
  networks:
  - name: ((default_network_name))           # cloud config 에 정의한 network 이름
    static_ips:
    - 10.30.107.122                          # 사용할 IP addresses 정의(필수): broker IP
  templates:
  - name: cubrid_broker  # job template 이름(필수)
    release: paasta-cubrid

- name: cubrid_broker_registrar
  azs:
  - z5
  instances: 1
  lifecycle: errand
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((default_network_name))
  properties:
      broker: # 서비스 브로커 설정 정보
        host: 10.30.107.122 # 서비스 브로커 IP 
        name: CubridDB  # CF에서 서비스 브로커를 생성시 생기는 서비스 이름 브로커에 고정되어있는 값
        password: cloudfoundry  # 브로커 접근 아이디 비밀번호(필수)
        username: admin   # 브로커 접근 아이디(필수)
        protocol: http
        port: 8088  # 브로커 포트
      cf:
        admin_password: admin   # CF 사용자의 패스워드
        admin_username: admin_test   # CF 사용자 이름
        api_url: https://api.115.68.46.189.xip.io   # CF 설치시 설정한 api uri 정보(필수)
  templates:
  - name: cubrid_broker_registrar  # job template 이름(필수)
    release: paasta-cubrid

- name: cubrid_broker_deregistrar
  azs:
  - z5
  instances: 1 
  lifecycle: errand
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((default_network_name))
  properties:
      broker: # 서비스 브로커 설정 정보
        host: 10.30.107.122 # 서비스 브로커 IP 
        name: CubridDB  # CF에서 서비스 브로커를 생성시 생기는 서비스 이름 브로커에 고정되어있는 값
        password: cloudfoundry  # 브로커 접근 아이디 비밀번호(필수)
        username: admin   # 브로커 접근 아이디(필수)
      cf:
        admin_password: admin   # CF 사용자의 패스워드
        admin_username: admin_test   # CF 사용자 이름
        api_url: https://api.115.68.46.189.xip.io   # CF 설치시 설정한 api uri 정보(필수)
  templates:
  - name: cubrid_broker_deregistrar  # job template 이름(필수)
    release: paasta-cubrid

properties:
  cubrid:   # Cubrid 설정 정보
    max_clients: 200
  cubrid_broker:  # Cubrid Servcice Broker 설정 정보
    cubrid_ip: 10.30.107.123 # Cubrid IP
    cubrid_db_port: 30000 # Cubrid Port
    cubrid_db_name: cubrid_broker   # Cubrid service 관리를 위한 데이터베이스 이름
    cubrid_db_user: dba   # 브로커 관리용 데이터베이스 접근 사용자이름
    cubrid_db_passwd: paasta  # 브로커 관리용 데이터베이스 접근 사용자 비밀번호
    cubrid_ssh_port: 22   # Cubrid가 설치된 서버 SSH 접속 포트
    cubrid_ssh_user: vcap # Cubrid가 설치된 서버 SSH 접속 사용자 이름
    cubrid_ssh_passwd: c1oudc0w # Cubrid가 설치된 서버 SSH 접속 사용자 비밀번호
    cubrid_ssh_sudo_passwd: c1oudc0w # Cubrid가 설치된 서버 sudo 비밀번호
    cubrid_ssh_identity: null # Cubrid가 설치된 서버 SSH 접속 인증 키/var/vcap/jobs/cubrid_broker/config/bosh.pem
    cubrid_ssh_key: null 
